/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

// Added for 'refreshVersions'
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    plugins {
        id("de.fayard.refreshVersions") version "0.60.5"
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    // id("org.gradle.toolchains.foojay-resolver-convention")
    // Auto upgrade dep versions
    id("de.fayard.refreshVersions")
}


rootProject.name = "TaskManager"
include("app")
