/*
 * This source file was generated by the Gradle 'init' task
 */
package TaskManager

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    @Test fun appHasAGreeting() {
        val timeStr = "01:02:03"
        val msg = "Time flies"
        val classUnderTest = Timer(timeStr, msg)
        assertEquals(classUnderTest.getMessage(), msg)
        assertEquals(classUnderTest.getSeconds(), 3723L)
    }
}
